alias gitlog='git log --graph --all --pretty=oneline'
alias ap='sudo ip netns exec ccu_dcu ssh 10.0.6.0'

alias builder5='ssh felipe@builder5.sonatus-internal'
alias builder7='ssh felipe@builder7.sonatus-internal'
alias tester1='ssh felipe@ccu-tester-1.sonatus-internal'
alias tester2='ssh felipe@ccu-tester-2.sonatus-internal'
alias tester3='ssh felipe@ccu-tester-3.sonatus-internal'
alias tester4='ssh felipe@ccu-tester-4.sonatus-internal'
alias tester5='ssh felipe@ccu-tester-5.sonatus-internal'
alias tester6='ssh felipe@ccu-tester-6.sonatus-internal'
alias tester7='ssh felipe@ccu-tester-7.sonatus-internal'
alias tester8='ssh felipe@ccu-tester-8.sonatus-internal'
alias tester9='ssh felipe@ccu-tester-9.sonatus-internal'
alias tester10='ssh felipe@ccu-tester-10.sonatus-internal'
alias tester11='ssh felipe@ccu-tester-11.sonatus-internal'

alias tester2-1='ssh felipe@ccu2-tester-1.sonatus-internal'
alias tester2-2='ssh felipe@ccu2-tester-2.sonatus-internal'
alias tester2-3='ssh felipe@ccu2-tester-3.sonatus-internal'
alias tester2-4='ssh felipe@ccu2-tester-4.sonatus-internal'
alias tester2-5='ssh felipe@ccu2-tester-5.sonatus-internal'
alias tester2-6='ssh felipe@ccu2-tester-6.sonatus-internal'
alias tester2-7='ssh felipe@ccu2-tester-7.sonatus-internal'
alias tester2-8='ssh felipe@ccu2-tester-8.sonatus-internal'
alias tester2-9='ssh felipe@ccu2-tester-9.sonatus-internal'
alias tester2-10='ssh felipe@ccu2-tester-10.sonatus-internal'
alias tester2-11='ssh felipe@ccu2-tester-11.sonatus-internal'
alias tester2-100='ssh felipe@ccu2-tester-100.sonatus-internal'
alias tester2-101='ssh felipe@ccu2-tester-101.sonatus-internal'
alias tester2-102'ssh felipe@ccu2-tester-102.sonatus-internal'




