# Mouse support:
# For tmux >= 2.1? 
set -g mouse on

# For tmux < 2.1:
#setw -g mode-mouse on
#set -g mouse-select-pane on
#set -g mouse-resize-pane on
#set -g mouse-select-window on

# Set the default terminal mode to 256color mode
set -g default-terminal "xterm-256color"

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Reload tmux in case it gets messed up:
bind-key r source-file ~/.tmux.conf; display "Reloaded!"

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefi

# Set the numbering of windows to go from 1 instead of 0:
set-option -g base-index 1
setw -g pane-base-index 1

# Bind [prefix] + <Ctrl-l> to clear the screen:
bind -n C-l send-keys 'C-l'


#======================================================
# tmux package manager (for tmux >= 1.9):

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Resurrect tmux sessions after machine reboot:
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-capture-pane-contents 'on'
# Key bindings:
#   - Save: [prefix] + Ctrl-s
#   - Restore: [prefix] + Ctrl-r

# Continuous saving of tmux environment: (requires tmux >= 1.9)
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

# Online Status Display:
set -g @plugin 'tmux-plugins/tmux-online-status'
set -g status-right "Online: #{online_status} | %a %h-%d %H:%M"


# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com/user/plugin'
# set -g @plugin 'git@bitbucket.com/user/plugin'

# To INSTALL a plugin: 
#   - add line in this file, like in the above examples
#   - [prefix] + I (from tmux emvironment)
# To UPDATE plugins:
#   - [prefix] + U
# To UNINSTALL a plugin:
#   - remove plugin ine from this file, or coment it out
#   - [prefix] + u

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
